Que.1 -
Data Description:
RI : refractive index
Na: Sodium (unit measurement: weight percent in corresponding oxide, as are attributes 4-10)
Mg: Magnesium
AI: Aluminum
Si: Silicon
K:Potassium
Ca: Calcium
Ba: Barium
Fe: Iron
Type: Type of glass: (class attribute)
 1 -- building_windows_float_processed
 2 --building_windows_non_float_processed
 3 --vehicle_windows_float_processed
 4 --vehicle_windows_non_float_processed (none in this database)
 5 --containers
 6 --tableware
 7 --headlamps

Dataset : Glass.csv

Prepare model by using Decision Tree, Random Forest , AdaBoost, CatBoost ,XGBoost & Calculate Accuracy by confusion matrix, Calculate accuracy score, precision score, recall score, f1 score.

### pre-requisites

In [3]:
import warnings
warnings.filterwarnings(action="ignore")

### import required packages

In [4]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

### load the data

In [5]:
df = pd.read_csv('glass.csv')
df.head()

RI     Na    Mg    Al     Si     K    Ca   Ba   Fe  Type
0  1.52101  13.64  4.49  1.10  71.78  0.06  8.75  0.0  0.0     1
1  1.51761  13.89  3.60  1.36  72.73  0.48  7.83  0.0  0.0     1
2  1.51618  13.53  3.55  1.54  72.99  0.39  7.78  0.0  0.0     1
3  1.51766  13.21  3.69  1.29  72.61  0.57  8.22  0.0  0.0     1
4  1.51742  13.27  3.62  1.24  73.08  0.55  8.07  0.0  0.0     1

### EDA

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 214 entries, 0 to 213
Data columns (total 10 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   RI      214 non-null    float64
 1   Na      214 non-null    float64
 2   Mg      214 non-null    float64
 3   Al      214 non-null    float64
 4   Si      214 non-null    float64
 5   K       214 non-null    float64
 6   Ca      214 non-null    float64
 7   Ba      214 non-null    float64
 8   Fe      214 non-null    float64
 9   Type    214 non-null    int64  
dtypes: float64(9), int64(1)
memory usage: 16.8 KB


In [7]:
df.isna().sum()

RI      0
Na      0
Mg      0
Al      0
Si      0
K       0
Ca      0
Ba      0
Fe      0
Type    0
dtype: int64

In [8]:
df['Type'].value_counts()

Type
2    76
1    70
7    29
3    17
5    13
6     9
Name: count, dtype: int64

In [9]:
from sklearn.preprocessing import LabelEncoder

df['Type'] = LabelEncoder().fit_transform(df['Type'])

In [10]:
df['Type'].value_counts()

Type
1    76
0    70
5    29
2    17
3    13
4     9
Name: count, dtype: int64

In [11]:
df.corr()

RI        Na        Mg        Al        Si         K        Ca  \
RI    1.000000 -0.191885 -0.122274 -0.407326 -0.542052 -0.289833  0.810403   
Na   -0.191885  1.000000 -0.273732  0.156794 -0.069809 -0.266087 -0.275442   
Mg   -0.122274 -0.273732  1.000000 -0.481799 -0.165927  0.005396 -0.443750   
Al   -0.407326  0.156794 -0.481799  1.000000 -0.005524  0.325958 -0.259592   
Si   -0.542052 -0.069809 -0.165927 -0.005524  1.000000 -0.193331 -0.208732   
K    -0.289833 -0.266087  0.005396  0.325958 -0.193331  1.000000 -0.317836   
Ca    0.810403 -0.275442 -0.443750 -0.259592 -0.208732 -0.317836  1.000000   
Ba   -0.000386  0.326603 -0.492262  0.479404 -0.102151 -0.042618 -0.112841   
Fe    0.143010 -0.241346  0.083060 -0.074402 -0.094201 -0.007719  0.124968   
Type -0.168739  0.506424 -0.728160  0.591198  0.149691 -0.025835 -0.008998   

            Ba        Fe      Type  
RI   -0.000386  0.143010 -0.168739  
Na    0.326603 -0.241346  0.506424  
Mg   -0.492262  0.083060 -0.728160  
Al    0.479404 -0.074402  0.591198  
Si   -0.102151 -0.094201  0.149691  
K    -0.042618 -0.007719 -0.025835  
Ca   -0.112841  0.124968 -0.008998  
Ba    1.000000 -0.058692  0.577676  
Fe   -0.058692  1.000000 -0.183207  
Type  0.577676 -0.183207  1.000000

### pre-processing

In [12]:
# split data into x and y
x = df[['Na','Mg','Al','Ba']]
y = df['Type']

In [13]:
# split the data into train and test
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(x, y, train_size=0.7, random_state=123456)

### train the models

#### Decision Tree

In [14]:
from sklearn.tree import DecisionTreeClassifier

def create_model_decision_tree():
    model = DecisionTreeClassifier(max_depth=50)
    model.fit(x_train, y_train)
    return model    

#### Random Forest

In [15]:
from sklearn.ensemble import RandomForestClassifier

def create_model_random_forest():
    model = RandomForestClassifier(n_estimators=100)
    model.fit(x_train, y_train)
    return model

#### CAT Boost

In [16]:
from catboost import CatBoostClassifier

def create_model_catboost():
    model = CatBoostClassifier(logging_level='Silent')
    model.fit(x_train, y_train)
    return model

#### AdaBoost

In [17]:
from sklearn.ensemble import AdaBoostClassifier

def create_model_ada_boost():
    model = AdaBoostClassifier()
    model.fit(x_train, y_train)
    return model

#### XGBoost

In [18]:
from xgboost import XGBClassifier

def create_model_xgboost():
    model = XGBClassifier()
    model.fit(x_train, y_train)
    return model

### model evaluation

In [22]:
from sklearn.metrics import confusion_matrix,accuracy_score, precision_score, recall_score, f1_score

def evaluate_model(model):
    # training accuracry
    y_pred = model.predict(x_train)
    y_true = y_train

    print(confusion_matrix(y_true, y_pred))

    # calculate training accuracy
    training_accuracy = accuracy_score(y_true, y_pred)

    # testing accuracy
    y_pred = model.predict(x_test)
    y_true = y_test

    print(confusion_matrix(y_true, y_pred))

    # get the performance metrics for testing
    testing_accuracy = accuracy_score(y_true, y_pred)
    testing_precision = precision_score(y_true, y_pred,average='micro')
    testing_recall = recall_score(y_true, y_pred,average='micro')
    testing_f1 = f1_score(y_true, y_pred,average='micro')

    return training_accuracy, testing_accuracy, testing_precision, testing_recall, testing_f1

### generate performance chart

In [23]:
models = [
    ("Decision Tree", create_model_decision_tree(), (0, 0)),
    ("Random Forest", create_model_random_forest(), (0, 1)),
    ("CAT Boost", create_model_catboost(), (1, 0)),
    ("Ada Boost", create_model_ada_boost(), (1, 1)),
    ("XGBoost", create_model_xgboost(), (2, 0))
]

In [24]:
performance_data = []
for model_name, model, position in models:
    train_accuracy, test_accuracy, precision, recall, f1 = evaluate_model(model)
    performance_data.append([
        model_name, f"{train_accuracy * 100:0.2f}%", f"{test_accuracy * 100:0.2f}%", precision, recall, f1
    ])
    
performance_chart = pd.DataFrame(performance_data, 
            columns=["Model", "Train Accuracy", "Test Accuracy", "Precision", "Recall", "F1"])
performance_chart

[[52  0  0  0  0  0]
 [ 0 53  0  0  0  0]
 [ 0  0 11  0  0  0]
 [ 0  0  0  8  0  0]
 [ 0  0  0  0  7  0]
 [ 0  0  0  0  0 18]]
[[15  2  1  0  0  0]
 [ 4 14  1  2  1  1]
 [ 5  0  1  0  0  0]
 [ 0  0  0  5  0  0]
 [ 0  0  0  0  1  1]
 [ 1  1  0  0  0  9]]
[[52  0  0  0  0  0]
 [ 0 53  0  0  0  0]
 [ 0  0 11  0  0  0]
 [ 0  0  0  8  0  0]
 [ 0  0  0  0  7  0]
 [ 0  0  0  0  0 18]]
[[16  2  0  0  0  0]
 [ 6 13  0  2  1  1]
 [ 6  0  0  0  0  0]
 [ 0  0  0  5  0  0]
 [ 0  0  0  0  2  0]
 [ 1  1  0  0  0  9]]
[[52  0  0  0  0  0]
 [ 0 53  0  0  0  0]
 [ 0  0 11  0  0  0]
 [ 0  0  0  8  0  0]
 [ 0  0  0  0  7  0]
 [ 0  0  0  0  0 18]]
[[16  2  0  0  0  0]
 [ 5 13  1  2  1  1]
 [ 6  0  0  0  0  0]
 [ 0  0  0  5  0  0]
 [ 0  0  0  0  1  1]
 [ 1  1  0  0  0  9]]
[[47  5  0  0  0  0]
 [36 16  0  0  1  0]
 [11  0  0  0  0  0]
 [ 0  5  0  3  0  0]
 [ 0  0  0  0  7  0]
 [ 0  0  0  0  1 17]]
[[18  0  0  0  0  0]
 [16  5  0  1  1  0]
 [ 6  0  0  0  0  0]
 [ 0  5  0  0  0  0]
 [ 0  0  0  0  2  0]
 [ 1  

Model Train Accuracy Test Accuracy  Precision    Recall        F1
0  Decision Tree        100.00%        69.23%   0.692308  0.692308  0.692308
1  Random Forest        100.00%        69.23%   0.692308  0.692308  0.692308
2      CAT Boost        100.00%        67.69%   0.676923  0.676923  0.676923
3      Ada Boost         60.40%        52.31%   0.523077  0.523077  0.523077
4        XGBoost        100.00%        66.15%   0.661538  0.661538  0.661538