Que.2 -
In this dataset you have to predict that customer is exited or not based on various factors given in dataset.

Dataset : Churn.csv
Steps to follow:
1. Do Proper EDA.
2. Drop Unnecessary Columns.
3. convert Categorical columns into numerical columns.

Prepare model by using Decision Tree, Random Forest, AdaBoost, CatBoost, XGBoost & Calculate Accuracy by confusion matrix, Calculate accuracy score, precision score, recall score, f1 score.

### pre-requisites

In [1]:
import warnings
warnings.filterwarnings(action="ignore")

### import required packages

In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

### load the data

In [3]:
df = pd.read_csv('Churn.csv')
df.head()

RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42   
1          2    15647311      Hill          608     Spain  Female   41   
2          3    15619304      Onio          502    France  Female   42   
3          4    15701354      Boni          699    France  Female   39   
4          5    15737888  Mitchell          850     Spain  Female   43   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4         79084.10       0

### EDA

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   RowNumber        10000 non-null  int64  
 1   CustomerId       10000 non-null  int64  
 2   Surname          10000 non-null  object 
 3   CreditScore      10000 non-null  int64  
 4   Geography        10000 non-null  object 
 5   Gender           10000 non-null  object 
 6   Age              10000 non-null  int64  
 7   Tenure           10000 non-null  int64  
 8   Balance          10000 non-null  float64
 9   NumOfProducts    10000 non-null  int64  
 10  HasCrCard        10000 non-null  int64  
 11  IsActiveMember   10000 non-null  int64  
 12  EstimatedSalary  10000 non-null  float64
 13  Exited           10000 non-null  int64  
dtypes: float64(2), int64(9), object(3)
memory usage: 1.1+ MB


In [5]:
df.isna().sum()

RowNumber          0
CustomerId         0
Surname            0
CreditScore        0
Geography          0
Gender             0
Age                0
Tenure             0
Balance            0
NumOfProducts      0
HasCrCard          0
IsActiveMember     0
EstimatedSalary    0
Exited             0
dtype: int64

In [6]:
df.drop(['RowNumber','CustomerId','Surname'],axis=1,inplace=True)

In [7]:
df.columns

Index(['CreditScore', 'Geography', 'Gender', 'Age', 'Tenure', 'Balance',
       'NumOfProducts', 'HasCrCard', 'IsActiveMember', 'EstimatedSalary',
       'Exited'],
      dtype='object')

In [8]:
df['Exited'].value_counts()

Exited
0    7963
1    2037
Name: count, dtype: int64

In [11]:
df_minority = df[df['Exited']==1]
df_majority = df[df['Exited']==0]

In [12]:
from sklearn.utils import resample

df_up_sampled = resample(df_minority,n_samples=7963,random_state=123456)
df_up_sampled

CreditScore Geography  Gender  Age  Tenure    Balance  NumOfProducts  \
306           731    France    Male   43       2       0.00              1   
3543          675    France    Male   49       8  135133.39              1   
2362          709   Germany    Male   45       4  122917.71              1   
5125          542     Spain    Male   54       8  105770.14              1   
7724          842    France    Male   44       3  141252.18              4   
...           ...       ...     ...  ...     ...        ...            ...   
1405          359    France  Female   44       6  128747.69              1   
5535          648   Germany  Female   32       8  157138.99              3   
4373          546     Spain  Female   45       2       0.00              1   
1454          521     Spain  Female   34       7   70731.07              1   
6913          564    France  Female   36       7  206329.65              1   

      HasCrCard  IsActiveMember  EstimatedSalary  Exited  
306           1               1        170034.95       1  
3543          0               1        179521.24       1  
2362          1               1            11.58       1  
5125          0               1        140929.98       1  
7724          0               1        128521.16       1  
...         ...             ...              ...     ...  
1405          1               0        146955.71       1  
5535          1               0        190994.48       1  
4373          0               0        197789.83       1  
1454          1               1         20243.97       1  
6913          1               1         46632.87       1  

[7963 rows x 11 columns]

In [13]:
df_balanced = pd.concat([df_up_sampled,df_majority])
df_balanced

CreditScore Geography  Gender  Age  Tenure    Balance  NumOfProducts  \
306           731    France    Male   43       2       0.00              1   
3543          675    France    Male   49       8  135133.39              1   
2362          709   Germany    Male   45       4  122917.71              1   
5125          542     Spain    Male   54       8  105770.14              1   
7724          842    France    Male   44       3  141252.18              4   
...           ...       ...     ...  ...     ...        ...            ...   
9993          644    France    Male   28       7  155060.41              1   
9994          800    France  Female   29       2       0.00              2   
9995          771    France    Male   39       5       0.00              2   
9996          516    France    Male   35      10   57369.61              1   
9999          792    France  Female   28       4  130142.79              1   

      HasCrCard  IsActiveMember  EstimatedSalary  Exited  
306           1               1        170034.95       1  
3543          0               1        179521.24       1  
2362          1               1            11.58       1  
5125          0               1        140929.98       1  
7724          0               1        128521.16       1  
...         ...             ...              ...     ...  
9993          1               0         29179.52       0  
9994          0               0        167773.55       0  
9995          1               0         96270.64       0  
9996          1               1        101699.77       0  
9999          1               0         38190.78       0  

[15926 rows x 11 columns]

In [14]:
df = df_balanced

In [15]:
df['Exited'].value_counts()

Exited
1    7963
0    7963
Name: count, dtype: int64

In [18]:
from sklearn.preprocessing import LabelEncoder

df['Geography'] = LabelEncoder().fit_transform(df['Geography'])

df['Gender'] = LabelEncoder().fit_transform(df['Gender'])

In [19]:
df.corr()

CreditScore  Geography    Gender       Age    Tenure  \
CreditScore         1.000000   0.002802 -0.010334 -0.006034  0.012785   
Geography           0.002802   1.000000  0.005056  0.022079 -0.018394   
Gender             -0.010334   0.005056  1.000000 -0.043140  0.005506   
Age                -0.006034   0.022079 -0.043140  1.000000 -0.025028   
Tenure              0.012785  -0.018394  0.005506 -0.025028  1.000000   
Balance             0.000765   0.082747  0.010698  0.052297 -0.000934   
NumOfProducts       0.014991   0.004399 -0.029867 -0.040670  0.019249   
HasCrCard          -0.014462  -0.021830  0.005524 -0.013812  0.016602   
IsActiveMember      0.018172  -0.003764  0.031977  0.016532 -0.025283   
EstimatedSalary    -0.028042  -0.011059 -0.017941 -0.000043  0.026958   
Exited             -0.037560   0.048066 -0.137013  0.349220 -0.021253   

                  Balance  NumOfProducts  HasCrCard  IsActiveMember  \
CreditScore      0.000765       0.014991  -0.014462        0.018172   
Geography        0.082747       0.004399  -0.021830       -0.003764   
Gender           0.010698      -0.029867   0.005524        0.031977   
Age              0.052297      -0.040670  -0.013812        0.016532   
Tenure          -0.000934       0.019249   0.016602       -0.025283   
Balance          1.000000      -0.176630  -0.007415       -0.032995   
NumOfProducts   -0.176630       1.000000  -0.002504        0.029897   
HasCrCard       -0.007415      -0.002504   1.000000       -0.040095   
IsActiveMember  -0.032995       0.029897  -0.040095        1.000000   
EstimatedSalary  0.003686       0.010772  -0.015549       -0.005611   
Exited           0.156278      -0.049003  -0.013441       -0.197930   

                 EstimatedSalary    Exited  
CreditScore            -0.028042 -0.037560  
Geography              -0.011059  0.048066  
Gender                 -0.017941 -0.137013  
Age                    -0.000043  0.349220  
Tenure                  0.026958 -0.021253  
Balance                 0.003686  0.156278  
NumOfProducts           0.010772 -0.049003  
HasCrCard              -0.015549 -0.013441  
IsActiveMember         -0.005611 -0.197930  
EstimatedSalary         1.000000  0.023588  
Exited                  0.023588  1.000000

### pre-processing

In [20]:
# split data into x and y
x = df[['Gender','Age','Balance','IsActiveMember']]
y = df['Exited']

In [21]:
# split the data into train and test
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(x, y, train_size=0.7, random_state=123456)

### train the models

#### Decision Tree

In [22]:
from sklearn.tree import DecisionTreeClassifier

def create_model_decision_tree():
    model = DecisionTreeClassifier(max_depth=50)
    model.fit(x_train, y_train)
    return model    

#### Random Forest

In [23]:
from sklearn.ensemble import RandomForestClassifier

def create_model_random_forest():
    model = RandomForestClassifier(n_estimators=100)
    model.fit(x_train, y_train)
    return model

#### CAT Boost

In [24]:
from catboost import CatBoostClassifier

def create_model_catboost():
    model = CatBoostClassifier(logging_level='Silent')
    model.fit(x_train, y_train)
    return model

#### AdaBoost

In [25]:
from sklearn.ensemble import AdaBoostClassifier

def create_model_ada_boost():
    model = AdaBoostClassifier()
    model.fit(x_train, y_train)
    return model

#### XGBoost

In [26]:
from xgboost import XGBClassifier

def create_model_xgboost():
    model = XGBClassifier()
    model.fit(x_train, y_train)
    return model

### model evaluation

In [27]:
from sklearn.metrics import confusion_matrix,accuracy_score, precision_score, recall_score, f1_score

def evaluate_model(model):
    # training accuracry
    y_pred = model.predict(x_train)
    y_true = y_train

    # calculate training accuracy
    training_accuracy = accuracy_score(y_true, y_pred)

    # testing accuracy
    y_pred = model.predict(x_test)
    y_true = y_test

    print(confusion_matrix(y_true, y_pred))

    # get the performance metrics for testing
    testing_accuracy = accuracy_score(y_true, y_pred)
    testing_precision = precision_score(y_true, y_pred,average='micro')
    testing_recall = recall_score(y_true, y_pred,average='micro')
    testing_f1 = f1_score(y_true, y_pred,average='micro')

    return training_accuracy, testing_accuracy, testing_precision, testing_recall, testing_f1

### generate performance chart

In [28]:
models = [
    ("Decision Tree", create_model_decision_tree(), (0, 0)),
    ("Random Forest", create_model_random_forest(), (0, 1)),
    ("CAT Boost", create_model_catboost(), (1, 0)),
    ("Ada Boost", create_model_ada_boost(), (1, 1)),
    ("XGBoost", create_model_xgboost(), (2, 0))
]

In [29]:
performance_data = []
for model_name, model, position in models:
    train_accuracy, test_accuracy, precision, recall, f1 = evaluate_model(model)
    performance_data.append([
        model_name, f"{train_accuracy * 100:0.2f}%", f"{test_accuracy * 100:0.2f}%", precision, recall, f1
    ])
    
performance_chart = pd.DataFrame(performance_data, 
            columns=["Model", "Train Accuracy", "Test Accuracy", "Precision", "Recall", "F1"])
performance_chart

[[1954  449]
 [ 318 2057]]
[[1943  460]
 [ 278 2097]]
[[1878  525]
 [ 655 1720]]
[[1790  613]
 [ 762 1613]]
[[1864  539]
 [ 544 1831]]


Model Train Accuracy Test Accuracy  Precision    Recall        F1
0  Decision Tree         92.75%        83.95%   0.839473  0.839473  0.839473
1  Random Forest         92.73%        84.55%   0.845542  0.845542  0.845542
2      CAT Boost         78.67%        75.30%   0.753035  0.753035  0.753035
3      Ada Boost         72.26%        71.22%   0.712223  0.712223  0.712223
4        XGBoost         83.68%        77.33%   0.773336  0.773336  0.773336