Que.4 

Implement a KNN,SVM and Naive Bayes model to classify the type of animals in the zoo in to different categories.
Also calculate Accuracy by confusion matrix, Calculate accuracy score, precision score, recall score, f1 score.

Dataset : Zoo.csv

### import required packages

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

### load the data

In [2]:
df = pd.read_csv('Zoo.csv')
df.head()

hair  feathers  eggs  milk  airborne  aquatic  predator  toothed  backbone  \
0     1         0     0     1         0        0         1        1         1   
1     1         0     0     1         0        0         0        1         1   
2     0         0     1     0         0        1         1        1         1   
3     1         0     0     1         0        0         1        1         1   
4     1         0     0     1         0        0         1        1         1   

   breathes  venomous  fins  legs  tail  domestic  catsize  type  
0         1         0     0     4     0         0        1     1  
1         1         0     0     4     1         0        1     1  
2         0         0     1     0     1         0        0     4  
3         1         0     0     4     0         0        1     1  
4         1         0     0     4     1         0        1     1

### exploratory data analysis

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 101 entries, 0 to 100
Data columns (total 17 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   hair      101 non-null    int64
 1   feathers  101 non-null    int64
 2   eggs      101 non-null    int64
 3   milk      101 non-null    int64
 4   airborne  101 non-null    int64
 5   aquatic   101 non-null    int64
 6   predator  101 non-null    int64
 7   toothed   101 non-null    int64
 8   backbone  101 non-null    int64
 9   breathes  101 non-null    int64
 10  venomous  101 non-null    int64
 11  fins      101 non-null    int64
 12  legs      101 non-null    int64
 13  tail      101 non-null    int64
 14  domestic  101 non-null    int64
 15  catsize   101 non-null    int64
 16  type      101 non-null    int64
dtypes: int64(17)
memory usage: 13.5 KB


In [4]:
df.isna().sum()

hair        0
feathers    0
eggs        0
milk        0
airborne    0
aquatic     0
predator    0
toothed     0
backbone    0
breathes    0
venomous    0
fins        0
legs        0
tail        0
domestic    0
catsize     0
type        0
dtype: int64

In [5]:
# check if the data is imbalanced
df['type'].value_counts()

type
1    41
2    20
4    13
7    10
6     8
3     5
5     4
Name: count, dtype: int64

In [6]:
df.cov()

hair  feathers      eggs      milk  airborne   aquatic  \
hair      0.246931 -0.085149 -0.201188  0.215446 -0.042178 -0.113267   
feathers -0.085149  0.160396  0.083168 -0.081188  0.112475 -0.011287   
eggs     -0.201188  0.083168  0.245347 -0.229505  0.079802  0.089703   
milk      0.215446 -0.081188 -0.229505  0.243564 -0.077426 -0.086139   
airborne -0.042178  0.112475  0.079802 -0.077426  0.182970 -0.035545   
aquatic  -0.113267 -0.011287  0.089703 -0.086139 -0.035545  0.231683   
predator -0.038416 -0.020891  0.002871 -0.007327 -0.063069  0.090396   
toothed   0.120297 -0.120792 -0.156337  0.152376 -0.124950  0.012574   
backbone  0.036634  0.035644 -0.064851  0.073069 -0.017228  0.004158   
breathes  0.089406  0.041584 -0.077327  0.085248  0.049901 -0.125149   
venomous -0.014059 -0.015842  0.013267 -0.032475  0.000990  0.011485   
fins     -0.052376 -0.033663  0.030693 -0.029010 -0.040396  0.109406   
legs      0.398119 -0.168317 -0.226535  0.214950  0.038020 -0.352970   
tail      0.010693  0.051485 -0.048119  0.045545  0.001782 -0.007327   
domestic  0.034653  0.004257 -0.025941  0.027228  0.009109 -0.036337   
catsize   0.112673 -0.027129 -0.127030  0.141386 -0.074554 -0.026832   
type     -0.587624 -0.166337  0.689307 -0.750990  0.020396  0.330594   

          predator   toothed  backbone  breathes  venomous      fins  \
hair     -0.038416  0.120297  0.036634  0.089406 -0.014059 -0.052376   
feathers -0.020891 -0.120792  0.035644  0.041584 -0.015842 -0.033663   
eggs      0.002871 -0.156337 -0.064851 -0.077327  0.013267  0.030693   
milk     -0.007327  0.152376  0.073069  0.085248 -0.032475 -0.029010   
airborne -0.063069 -0.124950 -0.017228  0.049901  0.000990 -0.040396   
aquatic   0.090396  0.012574  0.004158 -0.125149  0.011485  0.109406   
predator  0.249505  0.031782  0.009802 -0.053564  0.015644  0.035743   
toothed   0.031782  0.241584  0.108713 -0.013168 -0.008317  0.067327   
backbone  0.009802  0.108713  0.147921  0.032574 -0.025743  0.030297   
breathes -0.053564 -0.013168  0.032574  0.166337 -0.013366 -0.094653   
venomous  0.015644 -0.008317 -0.025743 -0.013366  0.073663 -0.003465   
fins      0.035743  0.067327  0.030297 -0.094653 -0.003465  0.141386   
legs     -0.101287 -0.193366 -0.338515  0.306733  0.012673 -0.463069   
tail      0.004158  0.067030  0.123663  0.015941 -0.019406  0.033762   
domestic -0.052079  0.011485  0.013168  0.017030 -0.000297 -0.011881   
catsize   0.036040  0.084257  0.068416  0.041485 -0.024851  0.005941   
type      0.064257 -0.487327 -0.670297 -0.445347  0.183465  0.078614   

              legs      tail  domestic   catsize      type  
hair      0.398119  0.010693  0.034653  0.112673 -0.587624  
feathers -0.168317  0.051485  0.004257 -0.027129 -0.166337  
eggs     -0.226535 -0.048119 -0.025941 -0.127030  0.689307  
milk      0.214950  0.045545  0.027228  0.141386 -0.750990  
airborne  0.038020  0.001782  0.009109 -0.074554  0.020396  
aquatic  -0.352970 -0.007327 -0.036337 -0.026832  0.330594  
predator -0.101287  0.004158 -0.052079  0.036040  0.064257  
toothed  -0.193366  0.067030  0.011485  0.084257 -0.487327  
backbone -0.338515  0.123663  0.013168  0.068416 -0.670297  
breathes  0.306733  0.015941  0.017030  0.041485 -0.445347  
venomous  0.012673 -0.019406 -0.000297 -0.024851  0.183465  
fins     -0.463069  0.033762 -0.011881  0.005941  0.078614  
legs      4.134653 -0.311188  0.050594  0.069703  0.563069  
tail     -0.311188  0.193069  0.003465  0.053267 -0.583762  
domestic  0.050594  0.003465  0.113267  0.003366 -0.128119  
catsize   0.069703  0.053267  0.003366  0.248317 -0.545941  
type      0.563069 -0.583762 -0.128119 -0.545941  4.421386

In [7]:
df.corr()

hair  feathers      eggs      milk  airborne   aquatic  \
hair      1.000000 -0.427851 -0.817382  0.878503 -0.198431 -0.473554   
feathers -0.427851  1.000000  0.419248 -0.410761  0.656553 -0.058552   
eggs     -0.817382  0.419248  1.000000 -0.938848  0.376646  0.376244   
milk      0.878503 -0.410761 -0.938848  1.000000 -0.366765 -0.362613   
airborne -0.198431  0.656553  0.376646 -0.366765  1.000000 -0.172638   
aquatic  -0.473554 -0.058552  0.376244 -0.362613 -0.172638  1.000000   
predator -0.154769 -0.104430  0.011605 -0.029721 -0.295181  0.375978   
toothed   0.492531 -0.613631 -0.642150  0.628168 -0.594311  0.053150   
backbone  0.191681  0.231403 -0.340420  0.384958 -0.104718  0.022463   
breathes  0.441149  0.254588 -0.382777  0.423527  0.286039 -0.637506   
venomous -0.104245 -0.145739  0.098689 -0.242449  0.008528  0.087915   
fins     -0.280313 -0.223541  0.164796 -0.156328 -0.251157  0.604492   
legs      0.394009 -0.206686 -0.224918  0.214196  0.043712 -0.360638   
tail      0.048973  0.292569 -0.221090  0.210026  0.009482 -0.034642   
domestic  0.207208  0.031586 -0.155610  0.163928  0.063274 -0.224308   
catsize   0.455020 -0.135934 -0.514650  0.574906 -0.349768 -0.111866   
type     -0.562384 -0.197520  0.661825 -0.723683  0.022677  0.326639   

          predator   toothed  backbone  breathes  venomous      fins  \
hair     -0.154769  0.492531  0.191681  0.441149 -0.104245 -0.280313   
feathers -0.104430 -0.613631  0.231403  0.254588 -0.145739 -0.223541   
eggs      0.011605 -0.642150 -0.340420 -0.382777  0.098689  0.164796   
milk     -0.029721  0.628168  0.384958  0.423527 -0.242449 -0.156328   
airborne -0.295181 -0.594311 -0.104718  0.286039  0.008528 -0.251157   
aquatic   0.375978  0.053150  0.022463 -0.637506  0.087915  0.604492   
predator  1.000000  0.129452  0.051022 -0.262931  0.115391  0.190302   
toothed   0.129452  1.000000  0.575085 -0.065690 -0.062344  0.364292   
backbone  0.051022  0.575085  1.000000  0.207666 -0.246611  0.209499   
breathes -0.262931 -0.065690  0.207666  1.000000 -0.120752 -0.617219   
venomous  0.115391 -0.062344 -0.246611 -0.120752  1.000000 -0.033956   
fins      0.190302  0.364292  0.209499 -0.617219 -0.033956  1.000000   
legs     -0.099723 -0.193476 -0.432856  0.369868  0.022964 -0.605652   
tail      0.018947  0.310368  0.731762  0.088952 -0.162724  0.204349   
domestic -0.309794  0.069430  0.101733  0.124068 -0.003252 -0.093887   
catsize   0.144790  0.344010  0.356976  0.204125 -0.183748  0.031705   
type      0.061179 -0.471527 -0.828845 -0.519308  0.321476  0.099430   

              legs      tail  domestic   catsize      type  
hair      0.394009  0.048973  0.207208  0.455020 -0.562384  
feathers -0.206686  0.292569  0.031586 -0.135934 -0.197520  
eggs     -0.224918 -0.221090 -0.155610 -0.514650  0.661825  
milk      0.214196  0.210026  0.163928  0.574906 -0.723683  
airborne  0.043712  0.009482  0.063274 -0.349768  0.022677  
aquatic  -0.360638 -0.034642 -0.224308 -0.111866  0.326639  
predator -0.099723  0.018947 -0.309794  0.144790  0.061179  
toothed  -0.193476  0.310368  0.069430  0.344010 -0.471527  
backbone -0.432856  0.731762  0.101733  0.356976 -0.828845  
breathes  0.369868  0.088952  0.124068  0.204125 -0.519308  
venomous  0.022964 -0.162724 -0.003252 -0.183748  0.321476  
fins     -0.605652  0.204349 -0.093887  0.031705  0.099430  
legs      1.000000 -0.348295  0.073931  0.068791  0.131693  
tail     -0.348295  1.000000  0.023434  0.243277 -0.631830  
domestic  0.073931  0.023434  1.000000  0.020073 -0.181043  
catsize   0.068791  0.243277  0.020073  1.000000 -0.521030  
type      0.131693 -0.631830 -0.181043 -0.521030  1.000000

In [8]:
# get all the relationships
correlation = df.corr()['type']

# remove the target column as it is 1.0
del correlation['type']

In [9]:
# get all absolute relationship magnitude
values = []
for value in correlation.values:
    values.append(abs(value))
values

[0.5623835244641703,
 0.19752035836900905,
 0.661825441989272,
 0.7236825854845621,
 0.022676515824113095,
 0.32663940873331754,
 0.0611793018681551,
 0.47152723973220184,
 0.8288452641993185,
 0.5193078656704727,
 0.3214763597798871,
 0.0994297824374027,
 0.13169311600669575,
 0.6318300243651724,
 0.18104284033345483,
 0.5210304273135065]

In [10]:
# find the min and max values
max = np.max(values)
min = np.min(values)
average_correlation = np.mean([min, max])
print(f"max = {max}, min = {min}, average = {average_correlation}")

max = 0.8288452641993185, min = 0.022676515824113095, average = 0.4257608900117158


In [11]:
# find the columns having correlation > average_correlation
columns = []
for index in range(len(correlation.values)):
    if abs(correlation.values[index]) >= average_correlation:
        columns.append(correlation.index[index])
columns

['hair', 'eggs', 'milk', 'toothed', 'backbone', 'breathes', 'tail', 'catsize']

### pre-processing

In [12]:
# split the data into x and y

x = df[columns]
y = df['type']
x

hair  eggs  milk  toothed  backbone  breathes  tail  catsize
0       1     0     1        1         1         1     0        1
1       1     0     1        1         1         1     1        1
2       0     1     0        1         1         0     1        0
3       1     0     1        1         1         1     0        1
4       1     0     1        1         1         1     1        1
..    ...   ...   ...      ...       ...       ...   ...      ...
96      1     0     1        1         1         1     1        1
97      1     1     0        0         0         1     0        0
98      1     0     1        1         1         1     1        1
99      0     1     0        0         0         1     0        0
100     0     1     0        0         1         1     1        0

[101 rows x 8 columns]

### split the data into train and test sets

In [13]:
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(x, y, train_size=0.7, random_state=123456)

### train the models

#### Naive Bayes

In [14]:
from sklearn.naive_bayes import GaussianNB

def create_naive_bayes_model():

    # create the model
    model = GaussianNB()

    # train the model
    model.fit(x_train, y_train)

    return model

#### KNN

In [15]:
from sklearn.neighbors import KNeighborsClassifier

def create_knn_model():

    # create the model
    model = KNeighborsClassifier(n_neighbors=5)

    # train the model
    model.fit(x_train, y_train)

    return model

#### SVM

In [16]:
from sklearn.svm import SVC

def create_svm_model():
    # create a model
    model = SVC()
    
    # train the model
    model.fit(x_train, y_train)

    return model

### model evaluation

In [17]:
from sklearn.metrics import confusion_matrix, accuracy_score, precision_score, recall_score, f1_score

def evaluate_model(model_name, model):
    
    # get the predictions using model
    y_pred = model.predict(x_test)
    y_true = y_test

    print(confusion_matrix(y_true, y_pred))
    
    # get the accuracy
    accuracy = accuracy_score(y_true, y_pred)

    # get the precision
    precision = precision_score(y_true, y_pred,average='micro')

    # get the recall
    recall = recall_score(y_true, y_pred,average='micro')

    # get f1 score
    f1 = f1_score(y_true, y_pred,average='micro')

    return model_name, accuracy, precision, recall, f1

In [18]:
# create Naive Bayes model
model_nb = create_naive_bayes_model()

# create KNN model
model_knn = create_knn_model()

# create SVM model
model_svm = create_svm_model()

In [19]:
# evaluate all the models
model_evaluation_params = pd.DataFrame([
    evaluate_model("Naive Bayes", model_nb),
    evaluate_model('KNN', model_knn), 
    evaluate_model('SVM', model_svm)
], columns=["Model Name", "Accuracy", "Precision", "Recall", "F1 Score"])

[[11  0  0  0  0  0  0]
 [ 0 10  0  0  0  0  0]
 [ 0  0  0  0  1  0  0]
 [ 0  0  0  4  0  0  0]
 [ 0  0  0  0  1  0  0]
 [ 0  0  0  0  0  1  0]
 [ 0  0  0  0  0  2  1]]
[[11  0  0  0  0  0  0]
 [ 0 10  0  0  0  0  0]
 [ 0  1  0  0  0  0  0]
 [ 0  0  0  4  0  0  0]
 [ 0  0  0  0  1  0  0]
 [ 0  0  0  0  0  1  0]
 [ 0  0  0  0  0  2  1]]
[[11  0  0  0  0  0  0]
 [ 0 10  0  0  0  0  0]
 [ 0  0  1  0  0  0  0]
 [ 0  0  0  4  0  0  0]
 [ 0  0  0  0  1  0  0]
 [ 0  0  0  0  0  1  0]
 [ 0  0  0  0  0  2  1]]


In [20]:
# performance chart
model_evaluation_params

Model Name  Accuracy  Precision    Recall  F1 Score
0  Naive Bayes  0.903226   0.903226  0.903226  0.903226
1          KNN  0.903226   0.903226  0.903226  0.903226
2          SVM  0.935484   0.935484  0.935484  0.935484